bartapi:
  url:
    etd: http://api.bart.gov/api/etd.aspx?cmd=etd&orig={station}&key={key}&json=y
    duration: http://api.bart.gov/api/sched.aspx?cmd=depart&orig={origin>=}&dest={destination}&key={key}&b=0&a=1&json=y

  key: MW9S-E7SL-26DU-VV8V
#Personal key: QRZB-5XUN-9JWT-DWE9


